#ifndef EXTI_CONFIG_H
#define EXTI_CONFIG_H

#define  EXTI_INT0_ENABLE ENABLE
#define  EXTI_INT1_ENABLE ENABLE
#define  EXTI_INT2_ENABLE ENABLE

#define EXTI_INT0_SENSE_CTRL FAILLING_EDGE
#define EXTI_INT1_SENSE_CTRL FAILLING_EDGE
#define EXTI_INT2_SENSE_CTRL FAILLING_EDGE

#endif
