#ifndef KPD_CONFIG
#define KPD_CONFIG

#define KPD_COLUMN_PORT PORTA

#define KPD_COLUMN0_PIN PIN0
#define KPD_COLUMN1_PIN PIN1
#define KPD_COLUMN2_PIN PIN2
#define KPD_COLUMN3_PIN PIN3 
#define KPD_ROW_PORT PORTC

#define KPD_ROW0_PIN PIN4
#define KPD_ROW1_PIN PIN5
#define KPD_ROW2_PIN PIN6
#define KPD_ROW3_PIN PIN7

#define KPD_KEYSARRAY_VALUES {{0,1,2,3},{4,5,6,7},{8,9,10,11},{12,13,14,15}}

#define KPD_NO_PRESSEDKEY 0xAA
#endif